### PR TITLE
added option for ssl connections

### PR DESCRIPTION
**Pull request by odobroiu**
Added the option of using ssl for connecting to the cassandra nodes.

Started this from the master branch( and not from the v2) as it should be easy to merge.

### CODE REVIEW

**Comment by iamaleksey** [comment]
The PR mostly LGTM, with some exceptions.

connect_option() in seestar_session would need to be updated, since it would no longer be accepting just gen_tcp:connect_option(), but ssl options too.

I'm also not sold on having 'ssl' as a boolean. I'd prefer to just look for 'cacertfile' in ConnectOptions, and, if found, use ssl, implicitly.

Also, this needs to be documented properly (good time to document start_link/4).

**Comment by odobroiu** [comment]
Added docs, updated connect_option(). 

About the {ssl, true}, would just like to say that looking for 'cacertfile' might not be enough, as it is possible to not have that option because you provide 'cacerts' , or maybe do not want to verify the certificate at all.

Of course, if you still think it's a better choice, will change that in the next few days and rebase.

**Comment by iamaleksey** [comment]
Thanks.

I guess, alternatively, an {ssl, SSLOptionsList} would also work, and better than the implicit reliance on 'cacertfile', which isn't trivial, as you mentioned.

**Comment by odobroiu** [comment]
Still not quite sure about the case when you want to just use ssl, and don't provide any options. You would pass {ssl, []} or maybe {ssl, true} and would still have to remove the tuple from the list.

Either way, will address this tomorrow as it's pretty late atm. :)

**Comment by iamaleksey** [comment]
LGTM, committed. Thanks (:

**Pull request merged**
